
# NYT article: http://mobile.nytimes.com/2015/09/14/upshot/gaps-in-alumni-earnings-stand-out-in-release-of-college-data.html?referrer=

# earnings by type of school (for-profit, non-profit, etc)
# $25K is about what high school graduates earn (median value)
# 10 years after enrolling

# percentage debt and something like eliteness?

# gender-related question like:
# Women who enrolled at elite colleges are making less than their male counterparts. The gap is largest at M.I.T.: $58,100. 
# Women who enrolled at Harvard are making as much as men who enrolled at Tufts.

# "At 53 percent of institutions, more
# than half of alumni are not even earning more than a typical high school graduate within six years after
# starting at the school."


# https://collegescorecard.ed.gov/data/

# Indicates that HS median income is actually higher:
# http://www.pewsocialtrends.org/2014/02/11/the-rising-cost-of-not-going-to-college/
# https://nces.ed.gov/fastfacts/display.asp?id=77

# Sticker price (note this is more involved than you've indicated):
# http://opendata.stackexchange.com/questions/6127/what-is-the-variable-that-closest-resembles-sticker-price

# "If your purpose is drawing comparisons to net price, it makes sense to use the cost of attendance variable 
# you indicated [COSTT4_A] because net price is generated by subtracting grant and scholarship aid from the total cost of attendance
# (not just tuition and fees). Total cost of attendance is the sum of published tuition and required fees (lower 
# of in-district or in-state for public institutions), books and supplies, and the weighted average for room and board and other expenses."

#download.file(url = "http://bit.ly/dasi_project_template", destfile = "dasi_project_template.Rmd")

source("http://bit.ly/dasi_inference")
set.seed(42)

data <- read.csv("https://s3.amazonaws.com/ed-college-choice-public/Most+Recent+Cohorts+(All+Data+Elements).csv", na.strings = c("NULL", "PrivacySuppressed"))
#data_treasury <- read.csv("https://s3.amazonaws.com/ed-college-choice-public/Most+Recent+Cohorts+(Treasury+Elements).csv", na.strings = c("NULL", "PrivacySuppressed"))
data$COSTT4 <- with(data, ifelse(is.na(COSTT4_A), COSTT4_P, COSTT4_A)) # select column with non-NA value
#data$cost_cat <- cut(data$COSTT4, 4) # divided evenly into 4 groups
cdata <- data[,c("COSTT4", "gt_25k_p10")]
cdata$cost_cat <- as.factor(findInterval(data$COSTT4, seq(0, 60000, by=10000))) # divided into 6 groups (may have zero count buckets)
cdata <- cdata[complete.cases(cdata),] # drop NA rows
cdata$COSTT4 <- NULL # Drop price column
# IS THIS NECESSARY WITH ANOVA?
cdata <- cdata[sample(nrow(cdata), round(nrow(data) / 10)),] # sample random rows (10% of total population)

inference(cdata$gt_25k_p10, cdata$cost_cat, est="mean", type = "ht", method = "theoretical", alternative = "greater")

hist(cdata$COSTT4, xlab="Cost in $", main ="Average Cost of Attendance")

plot(by(cdata$gt_25k_p10, cdata$costLevel, mean))

# maybe divide gt_25k into 4 levels ???
# This measure describes the fraction of former students earning over $25,000 in 2014 constant dollars (gt_25k_p*).
# or maybe use proportion value instead?

#cdata$costCut <- cut(cdata$COSTT4, 4) # divided evenly into 4 groups
#cdata$costLevel <- as.factor(findInterval(cdata$COSTT4, seq(0, 80000, by=5000))) # divided into 80/5 groups (may have zero count buckets)

